# Generated by Django 5.2.6 on 2025-12-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_promo_amount_order_promo_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_discount',
        ),
    ]
