# Generated by Django 5.2.6 on 2025-12-15 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_options_remove_cart_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='ID товара')),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Отлично'), (4, '⭐⭐⭐⭐ Хорошо'), (3, '⭐⭐⭐ Удовлетворительно'), (2, '⭐⭐ Плохо'), (1, '⭐ Очень плохо')], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о товаре',
                'verbose_name_plural': 'Отзывы о товарах',
                'ordering': ['-created_at'],
                'unique_together': {('product_id', 'user')},
            },
        ),
    ]
